controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\Dispositivos;
use app\models\DispositivosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Atenciones;
use app\models\Usuarios;
use app\models\UsuariosSearch;


class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public $dataProviderDispositivos = '';
    public $searchModelDispositivos = '';
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'index', 'getdatamarker', 'geodireccion', 'getdispositivosusuario', 'soporteatencion', 'asociadoperfil', 'asociadodashboard', 'asociadonotificaciones'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post']
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {            
        if ($action->id == 'geodireccion') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionGetdispositivosusuario(){
        $arrayDispositivos = array();
        // if( Yii::app()->user->getState('rol_id')==1 ){ //Super admin ve todos las flotas
        //  $flotas = null;
        // }elseif( Yii::app()->user->getState('rol_estaciones') == 1 ){ //Flotas dependen de estaciones
        //  $flotas = Util::getflotasOperador(Yii::app()->user->getState('usuario_id'));
         
        // }else{ //Flotas dependen de usuarios_flotas
        //  $flotas = Util::getflotasDespachador(Yii::app()->user->getState('usuario_id'));
        // }

        // if( Yii::app()->user->getState('rol_id')==9 ){ // Rol adminsitrador de granja
        //   $flotas = Util::getflotasAdminGranjas(Yii::app()->user->getState('usuario_id'));
        // }
        // $criteria = new CDbCriteria;
        // if( !is_null( $flotas ) ){
        //     $criteria->addInCondition('flota_id', $flotas);
        //     $dispositivos = Dispositivos::model()->findAll($criteria);
        // }else{
            $dispositivos = Usuarios::find()->andWhere(['es_asociado'=>1])->all();
        // }
        foreach ($dispositivos as $dispositivo) {
            $arrayDispositivos [] = array( 'id'=> $dispositivo->traccar_id, 'tipo'=>'' );
        }
        return json_encode($arrayDispositivos);
        
    }

    public function actionSoporteatencion( $id ){
        $request = Yii::$app->request;
        $atencion = Atenciones::findOne($id);
        $model = Usuarios::findOne( $atencion->paciente_id );
        $model->scenario = 'asignacion_doctor';
        if ( $model->load($request->post()) ) {

            $url = Yii::$app->params['api_utim'].'assigndoctor';
            // $url = 'http://localhost/geomonitoreo/web/api/pruebapost';

            $post_data['utim_atencion_id'] = $atencion->id;
            $post_data['doctor_id'] = $model->doctor_id;
            $post_data['latitude_inicial_doctor'] = $model->latitude_inicial_doctor;
            $post_data['longitude_inicial_doctor'] = $model->longitude_inicial_doctor;
            $post_data['tiempo_atencion'] = $model->tiempo_atencion;

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_VERBOSE, 1);
            $response = curl_exec($ch);
            $response = json_decode( $response );

            if( $response->status == 1 ){
                return $this->redirect(['index']);
            }else{
                $doctor = Usuarios::findOne( $model->doctor_id );
                Yii::$app->getSession()->setFlash('success', [
                    'type' => 'danger',
                    'duration' => 15000,
                    'icon' => 'glyphicon glyphicon-ok-sign',
                    'message' => 'Se ha asignado al Dr(a). '.$doctor->nombres.' '.$model->apellidos.' a otra atención, por favor asigne otro doctor',
                    'title' => 'Geomonitoreo',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            } 
        }

        return $this->render( 'soporte_atencion', [ 'model'=>$model, 'atencion'=>$atencion ] );
    }

    public function actionGetdatamarker($traccar_id){
        $html = '';

        
            $usuario = Usuarios::find()->andWhere([ 'traccar_id'=>$traccar_id ])->one();
            if( is_object( $usuario ) ){
                        $html.= '<h2>Información del Asociado</h2>';
                        $html.= '<table id="" class="detail-view table table-striped table-condensed">
                                <tbody>
                                    <tr>
                                        <th>Identificación</th>
                                        <td>'.$usuario->identificacion.'</td>
                                    </tr>
                                    <tr>
                                        <th>Nombres</th>
                                        <td>'.$usuario->nombres.'</td>
                                    </tr>
                                    <tr>
                                        <th>Apellidos</th>
                                        <td>'.$usuario->apellidos.'</td>
                                    </tr>
                                    <tr>
                                        <th>Número de celular</th>
                                        <td>'.$usuario->numero_celular.'</td>
                                    </tr>
                                    <tr>
                                        <th>E-mail</th>
                                        <td>'.$usuario->email.'</td>
                                    </tr>
                                </tbody>
                            </table>';
            }else{
                $html.= 'Información no disponible';
            }
        
        return $html;
    }

    public function actionGeodireccion(){
        $lat = trim($_POST['lat']);
        $lng = trim($_POST['lng']);
        $gmaps = 'https://maps.googleapis.com/maps/api/geocode/json?latlng='.$lat.','.$lng.'&key='.Yii::$app->params['google_key'];
        // $gmapsArray = file_get_contents($gmaps);

        $arrContextOptions=array(
        "ssl"=>array(
                "verify_peer"=>false,
                "verify_peer_name"=>false,
            ),
        );  
        $gmapsJson = file_get_contents($gmaps, false, stream_context_create($arrContextOptions));

        $gmapsArray = json_decode($gmapsJson);
        if( isset( $gmapsArray->results[0]->formatted_address ) ){
            return $gmapsArray->results[0]->formatted_address;
        }else{
            return 'No disponible';
        }
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if( Yii::$app->user->identity->es_asociado == 1 ){
            $this->layout = 'dashboard_asociado';
            Yii::$app->getSession()->setFlash('success', [
                'type' => 'success',
                'duration' => 5000,
                'icon' => 'glyphicon glyphicon-ok-sign',
                'message' => 'Por ahora no tiene notificaciones',
                'title' => 'Notificaciones',
                'positonY' => 'top',
                'positonX' => 'right'
            ]);
            return $this->render('asociado_dashboard',[

            ]);
        }
        if( Yii::$app->user->identity->es_super == 1 ){
            Yii::$app->getSession()->setFlash('success', [
                'type' => 'success',
                'duration' => 5000,
                'icon' => 'glyphicon glyphicon-ok-sign',
                'message' => 'Espere unos segundos mientras se cargan los dispositivos ...',
                'title' => 'Geomonitoreo',
                'positonY' => 'top',
                'positonX' => 'right'
            ]);
            $this->searchModelDispositivos = new UsuariosSearch();
            $this->dataProviderDispositivos = $this->searchModelDispositivos->searchAsociados(Yii::$app->request->queryParams);

            return $this->render('index', [
                
            ]);
        }

    }

        /**
     * Displays perfil Asociado.
     *
     * @return string
     */
    public function actionAsociadoperfil()
    {
        if( Yii::$app->user->identity->es_asociado == 1 ){
            $this->layout = 'dashboard_asociado';
            return $this->render('asociado_perfil',[

            ]);
        }
    }

    /**
     * Displays perfil Asociado.
     *
     * @return string
     */
    public function actionAsociadonotificaciones()
    {
        if( Yii::$app->user->identity->es_asociado == 1 ){
            $this->layout = 'dashboard_asociado';
            return $this->render('asociado_notificaciones',[

            ]);
        }
    }

            /**
     * Displays dashboard Asociado.
     *
     * @return string
     */
    public function actionAsociadodashboard()
    {
        if( Yii::$app->user->identity->es_asociado == 1 ){
            $this->layout = 'dashboard_asociado';

views/site/_columns_atenciones.php
<?php
use yii\helpers\Url;
use kartik\grid\GridView;
use yii\helpers\Html;

return [
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'paciente_id',
        'format'=>'raw',
        'value'=>function ($model, $key, $index, $widget) {
            return $model->paciente->nombres.' '.$model->paciente->apellidos;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'doctor_id',
        'format'=>'raw',
        'value'=>function ($model, $key, $index, $widget) {
            if( isset( $model->doctor ) ){
                return $model->doctor->nombres.' '.$model->doctor->apellidos;
            }else{
                return null;
            }
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'tiempo_atencion',
        'format'=>'raw',
        'value'=>function ($model, $key, $index, $widget) {
            if( $model->tiempo_atencion > 0 ){
                return $model->tiempo_atencion.' min';
            }else{
                return null;
            }
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'fecha_creacion',
    ],
    [
        'attribute'=>'estado',
        'filter'=>false,
        'width'=>'140px',
        'hAlign' => 'center',
        'value'=>function ($model, $key, $index, $widget) {
            $color = 'default';
            $texto = '';
            if( $model->estado == 0 ){
                $color = 'danger';
                $texto = 'Nueva atención';
            }elseif( $model->estado == 1 ){
                $color = 'warning';
                $texto = 'Doctor asignado';
            }elseif( $model->estado == 2 ){
                $color = 'success';
                $texto = 'Doctor atendiendo';
            }
            return '<a href="'.Url::to(['site/soporteatencion','id'=>$model->id]).'"><span class="btn-block btn-xs btn-'.$color.'">'.$texto.'</span></a>';
            // return Html::a('Ajax Link Label','#', [
            //     'title' => 'Ajax Title',
            //     'onclick'=>"
            //      $.ajax({
            //     type     :'get',
            //     cache    : false,
            //     data: {id: ".$model->id."},
            //     url  : '".Url::to(['atenciones/update'])."',
            //     success  : function(response) {
            //             console.log('success: '+response.filename);
            //     },
            //     error: function(){
            //       console.log('failure');
            //     }
            //     });return false;",
            //     'aria-label'=>'Atención',
            //     'data-pjax'=>'0',
            //     'role'=>'modal-remote',
            //     'data-toggle'=>'tooltip'
            // ]);

        },
        'format'=>'raw'
    ],
];   

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/asociado_dashboard.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuariosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<h4>Dashboard</h4>

<div class="row">
    <div class="dashboard-panel col-md-6">
        <div class="dashboard-panel-wrapper">
            <div class="dashboard-panel-header">Pedidos</div>
            <div class="dashboard-panel-content">
                <div class="dashboard-panel-content-item">
                <i>Por el momento no tiene ningún pedido.</i>
                </div>
            </div>
            <div class="dashboard-panel-footer">
                Ver todos los pedidos
            </div>
        </div>
    </div>

    <div class="dashboard-panel col-md-6">
        <div class="dashboard-panel-wrapper">
            <div class="dashboard-panel-header">Historial</div>
            <div class="dashboard-panel-content">
                <div class="dashboard-panel-content-item">
                <i>Por el momento no tiene ninguna notificación.</i>
                </div>
            </div>
            <div class="dashboard-panel-footer">
                Ver historial completo
            </div>
        </div>
    </div>
    

</div>

views/site/asociado_notificaciones.php
<script>
    document.getElementById("asoc-dash").classList.remove("active");
    document.getElementById("asoc-notif").classList.add("active");
</script>
<h4>Notificaciones</h4>
<h5>Por el momento no tiene ninguna notificación.</h5>

views/site/asociado_perfil.php
<script>
    document.getElementById("asoc-dash").classList.remove("active");
    document.getElementById("asoc-prof").classList.add("active");
</script>
<h4>Perfil</h4>
<div class="row">
    <div class="col-md-2">
        <img class="img-profile" src="<?= Yii::$app->user->identity->imagen ?>">
    </div>
    <div class="col-md-10">
        <h5><b>Estado</b></h5>
        <p><img class="asoc-estado" src="/images/<?php echo (Yii::$app->user->identity->estado == 1 ? "on": "off"); ?>.png"> <?=  Yii::$app->params['parametros_globales']['estados'][Yii::$app->user->identity->estado] ?></p>
        <hr>
        <h5><b>Nombre</b></h5>
        <p><?= Yii::$app->user->identity->nombres ?> <?= Yii::$app->user->identity->apellidos ?> </p>
        <h5><b>Email</b></h5>
        <p><?= Yii::$app->user->identity->email ?></p>
        <h5><b>Identificacion</b></h5>
        <p><?= Yii::$app->user->identity->identificacion ?> </p>
        <h5><b>Número celular</b></h5>
        <p><?= Yii::$app->user->identity->numero_celular ?></p>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;
use app\models\Util;
use app\models\Traccar;
CrudAsset::register($this);

$this->title = 'Geomonitoreo';
?>


<div id="a" class="split split-horizontal menu-panel">
  <div id="d" class="split content">
    <?=$this->render('../layouts/_partials/_menu_monitoreo.php')?>
  </div>
</div>
<div id="b" class="split split-horizontal">
  
  <!-- <div id="e" class="split content">     -->
      <div id="map_canvas" class="map_canvas"></div>
        <div id="search-options">
          <?php 
              // $this->widget('zii.widgets.jui.CJuiAutoComplete',array(
              //     'name'=>'auto_complete_producto_busqueda_rapida',
              //     'source'=>$this->createUrl('ajax/listadozonasmapa'),
              //       'options'=>array(
              //         'showAnim'=>'fold',
              //         'select' => 'js:function(event, ui){ centrar_poligono(ui.item.poligono) }',
              //         'change' => 'js:function(event, ui){
              //           if(ui.item===null){
              //             $("#auto_complete_producto_busqueda_rapida").val("");
              //           }            
              //         }',
              //       ),
              //       'htmlOptions'=>array(
              //         'class'=>'pac-input', 
              //         'placeholder'=>'Buscar lugares ...',
              //       ),
              // ));
            ?>

          <input id="pac-input" class="pac-input" type="text" placeholder="Buscar lugares ...">
          <!-- <select id="pac-input-select">
            <option value="G">Google</option>
            <option value="Z">Zonas</option>
          </select> -->
        </div>
  <!-- </div> -->
  
</div>

<style type="text/css">
.kv-panel-before, .kv-panel-after{
  display: none;
}
.panel-primary{
  border-color: transparent;
}
a:hover{
  text-decoration: none!important;
}
.panel{
  margin-bottom: 0!important;
}
</style>

views/site/index_back.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;
use app\models\Util;
use app\models\Traccar;
CrudAsset::register($this);

$this->title = 'Geomonitoreo';
?>


<div id="a" class="split split-horizontal menu-panel">
  <div id="d" class="split content">
    <?=$this->render('../layouts/_partials/_menu_monitoreo.php')?>
  </div>
</div>
<div id="b" class="split split-horizontal">
  
  <div id="e" class="split content">    
      <div id="map_canvas" class="map_canvas"></div>
        <div id="search-options">
          <?php 
              // $this->widget('zii.widgets.jui.CJuiAutoComplete',array(
              //     'name'=>'auto_complete_producto_busqueda_rapida',
              //     'source'=>$this->createUrl('ajax/listadozonasmapa'),
              //       'options'=>array(
              //         'showAnim'=>'fold',
              //         'select' => 'js:function(event, ui){ centrar_poligono(ui.item.poligono) }',
              //         'change' => 'js:function(event, ui){
              //           if(ui.item===null){
              //             $("#auto_complete_producto_busqueda_rapida").val("");
              //           }            
              //         }',
              //       ),
              //       'htmlOptions'=>array(
              //         'class'=>'pac-input', 
              //         'placeholder'=>'Buscar lugares ...',
              //       ),
              // ));
            ?>

          <input id="pac-input" class="pac-input" type="text" placeholder="Buscar lugares ...">
          <!-- <select id="pac-input-select">
            <option value="G">Google</option>
            <option value="Z">Zonas</option>
          </select> -->
        </div>
  </div>

  <div id="f" class="split content alert-panel">
    
    <div class="atenciones-index">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
                'id'=>'crud-datatable',
                'dataProvider' => $dataProvider,
                // 'filterModel' => $searchModel,
                'pjax'=>true,
                'columns' => require(__DIR__.'/_columns_atenciones.php'),
                'toolbar'=> [
                    ['content'=>
                        Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
                        ['role'=>'modal-remote','title'=> 'Create new Atenciones','class'=>'btn btn-default']).
                        Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                        ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
                        '{toggleData}'.
                        '{export}'
                    ],
                ],          
                'striped' => true,
                'condensed' => true,
                'responsive' => true,          
                'panel' => [
                    'type' => 'primary', 
                    'heading' => '<i class="glyphicon glyphicon-list"></i> Atenciones Historial',
                    // 'before'=>'<em>* Resize table columns just like a spreadsheet by dragging the column edges.</em>',
                    // 'after'=>BulkButtonWidget::widget([
                    //             'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
                    //                 ["bulk-delete"] ,
                    //                 [
                    //                     "class"=>"btn btn-danger btn-xs",
                    //                     'role'=>'modal-remote-bulk',
                    //                     'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    //                     'data-request-method'=>'post',
                    //                     'data-confirm-title'=>'Are you sure?',
                    //                     'data-confirm-message'=>'Are you sure want to delete this item'
                    //                 ]),
                    //         ]).                        
                    //         '<div class="clearfix"></div>',
                ]
            ])?>
        </div>
    </div>
    <?php Modal::begin([
        "id"=>"ajaxCrudModal",
        "footer"=>"",// always need it for jquery plugin
    ])?>
    <?php Modal::end(); ?>

  </div>
</div>

<style type="text/css">
.kv-panel-before, .kv-panel-after{
  display: none;
}
.panel-primary{
  border-color: transparent;
}
a:hover{
  text-decoration: none!important;
}
.panel{
  margin-bottom: 0!important;
}
</style>

views/site/index_visitas.php
<h2>Visitas para el <?php echo date('Y-m-d'); ?></h2>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php 
  // echo Yii::$app->getSecurity()->generatePasswordHash('admin');
?>
    <div class="row-fluid">
      <div class="col-md-4 col-md-offset-4">
          <div class="login-panel panel panel-default">
              <div class="panel-heading">
                  <div class="col-sm-offset-0">
                    <?= Html::img( Url::to('@web/images/logo-login.png'), ['class'=> 'login-logo center-block']);?>
                  </div>
                 <!--  <div class="col-md-offset-0"><h3><i>Iniciar Sesión<i></h3></div> -->
              </div>
              <div class="panel-body">
                  <?php $form = ActiveForm::begin([
                      'id' => 'login-form',
                      // 'layout' => 'horizontal',
                      'fieldConfig' => [
                          'template' => "{label}\n{input}\n{error}",
                          // 'labelOptions' => ['class' => 'col-lg-1 control-label'],
                      ],
                  ]); ?>
                          <?= $form->field($model, 'username', ['template' => '
                                 <div class="input-group col-sm-12 ">
                                    <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-user"></span>
                                    </span>
                                    {input}
                                 </div>
                                 {error}{hint}
                             ']
                             )->textInput(['autofocus' => true, 'class'=>'form-control', 'placeholder'=>'Ingrese su e-mail']) ?>

                          <?= $form->field($model, 'password', ['template' => '
                                 <div class="input-group col-sm-12 ">
                                    <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-lock"></span>
                                    </span>
                                    {input}
                                 </div>
                                 {error}{hint}
                             ']
                             )->passwordInput(['placeholder'=>'Ingrese su contraseña']) ?>
                          <!-- <a href="#" class="pull-right label-forgot">Olvido su contraseña?</a>                     -->
                          <?= $form->field($model, 'rememberMe')->checkbox([
                              // 'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
                          ]) ?>
                      
                      <?= Html::submitButton('Ingresar', ['class' => 'btn btn-primary btn-block btn-lg', 'name' => 'login-button']) ?>
                  <?php ActiveForm::end(); ?>
                  <!-- <div class="registrarse">
                      <div class="col-sm-offset-0"><p>¿No tienes una cuenta?</p></div>
                      <div class="col-md-4 col-md-offset-4"><p class="register"><a href="#">Registrarse</a></p></div>
                  </div> -->
              </div>
          </div>
          <div class="footer">
              <div class="col-sm-offset-0">
                <center><a href="https://youneed.com.ec/app/recuperarclave" target="_blank">¿Olvidaste tu contraseña?</a></center>
              </div>
          </div>
      </div><!-- /.col-->
  </div><!-- /.row -->